// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testProjEmpl.Models;

namespace testProjEmpl.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20201201204517_fixDb")]
    partial class fixDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("testProjEmpl.Models.Employee", b =>
                {
                    b.Property<int>("idEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("payment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idEmp")
                        .HasName("Employee_Pk");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("testProjEmpl.Models.EmployementHistory", b =>
                {
                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<int>("position_id")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("until")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employee_id", "position_id");

                    b.HasIndex("position_id");

                    b.ToTable("employementHistory");
                });

            modelBuilder.Entity("testProjEmpl.Models.Position", b =>
                {
                    b.Property<int>("idPosiotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idPosiotion")
                        .HasName("Position_Pk");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("testProjEmpl.Models.EmployementHistory", b =>
                {
                    b.HasOne("testProjEmpl.Models.Employee", "employee")
                        .WithMany("employemntHistory")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testProjEmpl.Models.Position", "position")
                        .WithMany("employemntHistory")
                        .HasForeignKey("position_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("position");
                });

            modelBuilder.Entity("testProjEmpl.Models.Employee", b =>
                {
                    b.Navigation("employemntHistory");
                });

            modelBuilder.Entity("testProjEmpl.Models.Position", b =>
                {
                    b.Navigation("employemntHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
